---

  - name: Cleanup WebGoat7 and Sheepdog
    hosts: localhost
    gather_facts: false
    vars:
      wg7_destination: ~/webgoat7
      pc_destination: ~/spring-petclinic

    tasks:
      - name: Remove Webgoat7 destination directory if it exists
        file:
          path: '{{item}}'
          state: absent
        with_items:
          - "{{wg7_destination}}"
          - "{{pc_destination}}"
